# Generated by Django 4.1.1 on 2022-10-05 16:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=75)),
                ('last_name', models.CharField(blank=True, max_length=75)),
                ('metAt', models.CharField(blank=True, max_length=150)),
                ('city', models.CharField(blank=True, max_length=75)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=75)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('socials', models.CharField(blank=True, max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('date_created', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UserCustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connectbetterapi.fieldtype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_custom_fields', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_categories', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomFieldContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_content', to='connectbetterapi.contact')),
                ('user_custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_content', to='connectbetterapi.usercustomfield')),
            ],
        ),
        migrations.CreateModel(
            name='ContactCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_categories', to='connectbetterapi.contact')),
                ('user_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts_using', to='connectbetterapi.usercategory')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='categories',
            field=models.ManyToManyField(related_name='contact_categories', through='connectbetterapi.ContactCategory', to='connectbetterapi.usercategory'),
        ),
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_contacts', to=settings.AUTH_USER_MODEL),
        ),
    ]
